version: 1.2.0+{build}
skip_tags: true
image:
- Visual Studio 2017
- Ubuntu
configuration: CI
before_build:
- pwsh: dotnet restore --verbosity m
build:
  verbosity: minimal
test_script:
- pwsh: build/appveyor.ps1
artifacts:
- path: artifacts/*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 7exHzq8I96c5RKQn+R6bho0U4DdjiO/vEvdZtXge+dmoHMhzIHzgEX+uDl1zuKj/
  artifact: nupkg
  on:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    branch: master
